project:
  type: website
  output-dir: docs
lang: fr
 
website:
  search: false
  title: ""
  navbar:
    background: "white"
    title: ""
    logo: "logo.png"
    collapse-below: lg
    left:
      - text: "R"
        href: R/index.qmd
      - text: "Othe-R"
        menu: 
          - text: "Quarto-Git-Python..."
            href: Autres/index.qmd
          - text: "Stata"
            href: Stata/index.qmd
      - text: "Autres Supports"
        href:  supports.qmd
    right: 
      - text: "{{< fa  info-circle>}}"
        href: about.qmd
      - text: "{{< fa brands github>}}"
        href: https://github.com/mthevenin/assistoolsms 


page-navigation: true
back-to-top-navigation: false


format:
  html:
    theme: [lux, sms.scss]
    css: sms.css
    toc: true
    code-link: true
    grid:
      sidebar-width: 350px
      body-width: 950px
      margin-width: 300px
      gutter-width: 1.5rem
    mainfont: "roboto"    
    code-line-numbers: false
    code-copy: true
#    code-tools:
#    source: true
highlight-style: atom-one

lightbox: true

execute: 
  freeze: auto

comments:
  giscus:
    repo: mthevenin/assistoolsms
