project:
  type: website
  output-dir: docs
lang: fr
 
website:
  search: false
  title: "SMS_site"
  navbar:
    background: "white"
    logo: img/coding2.png
    title: false
    collapse-below: lg
    left:
      - text: "R"
        href: R/index.qmd
      - text: "Othe-R"
        href: Autres/index.qmd
      - text: "Autres Supports"
        href: supports.qmd

page-navigation: true
back-to-top-navigation: false

page-footer:
    background: "#000000"
    center:  
      - href: https://github.com/mthevenin/assistoolsms
        icon: github
        aria-label: GitHub

format:
  html:
    theme: [lux, sms.scss]
    css: sms.css
    toc: true
    grid:
      sidebar-width: 350px
      body-width: 950px
      margin-width: 300px
      gutter-width: 1.5rem
    mainfont: "roboto"    
    code-line-numbers: true
    code-copy: true
    code-tools:
      source: true
highlight-style: dracula

execute: 
  freeze: auto

comments:
  giscus:
    repo: mthevenin/assistoolsms
