project:
  type: website
  output-dir: docs
lang: fr
 
website:
  title: "SMS_site"
  navbar:
    background: "white"
    logo: img/coding2.png
    logo-alt: "Logo Sms"
    title: false
    collapse-below: lg
    right:
      - text: "Base d'assistances"
        menu: 
          - text: "R"
            href: R/index.qmd
          - text: "Quarto"
            href: Quarto/index.qmd
          - text: "Autres"
            href: Autres/index.qmd
      - text: "Séminaires"      
        href: seminaire/seminaire.qmd
      - text: "Autres Supports"
        menu: 
          - text: "Stata"
            href: https://mthevenin.github.io/stata_fr/index.html
          - text: "Analyse textuelle"
            href: https://benegarbi.github.io/AtelierQO_R/

page-navigation: true
back-to-top-navigation: false

page-footer:
    background: "#000000"
    left: |
      Copyright &copy; 2023 [Institut National d'Etudes Démographiques](https://ined.fr/)
    center:  
      - href: https://github.com/mthevenin
        icon: github
        aria-label: GitHub

format:
  html:
    theme: [lux, sms.scss]
    css: sms.css
    toc: true
    grid:
     sidebar-width: 50px
     body-width:    1200px
     margin-width:  500px
     gutter-width: 2.5rem      
    code-line-numbers: true
    code-copy: true
    code-tools:
      source: true
highlight-style: dracula

execute: 
  freeze: auto


