{
  "hash": "e26afb49d923381a77f12ce942fc90f1",
  "result": {
    "markdown": "---\ntitle: \"Statistiques descriptives à partir d'enquêtes DHS\"\n\ndate: 07/19/2023\n  \ncategories:\n  - Recodage\n  - Statistiques descriptives\n\nauthor: \n  - name: \"Bénédicte Garnier\"\n    affiliations:\n      - name: \"Ined\"\n\nimage: \"https://www.globaldietarydatabase.org/sites/default/files/inline-images/dhs%20logo%203x2_0.png\"\n\nfilters:\n   - lightbox\nlightbox: auto\n\nabstract: | \n Nous allons montrer comment s'approprier des données issues des **Enquêtes Démographiques et de Santé** (DHS) pour produire des statistiques univariées avec R.\n\n---\n\n\n\n| Packages        | Fonctions                                 |\n|-----------------|-------------------------------------------|\n| **readstata13** | `read.dta13`                              |\n| **rio**         | `factorize`                               |\n| **dyplyr**      |  `mutate` `group by` `summerize`          |\n| **questionr**   | `freq`                                    |\n| **Base R**      | `str - summary`                           |\n\n: **Fonctions utilisées dans la fiche**\n\nLes [enquêtes Démographiques et de Santé (DHS)](http://dhsprogram.com/) sont régulièrement utilisées par les chercheurs travaillant sur le continent africain, l'amérique centrale et du sud ou l'asie du sud. \n\nLes fichiers issus de questionnaires *Ménages*, *Femmes* et *Hommes* ont la même structure dans tous les pays participant à chaque phase de l'enquête : 400 enquêtes dans 90 pays en 2023. Les régles de recodage sont définies dans le [Standard recode manuel DHS 6](www.dhsprogram.com/pubs/pdf/DHSG4/Recode6_DHS_22March2013_DHSG4.pdf)\n\nCet exemple s'inspire des fiches pédagogiques produites dans le cadre de l'[école d'été du Collège International des Sciences Territoriales](http://ee2023.netlify.app/) avec la lecture de fichiers téléchargés, l'identification des types de variables et la production d'indicateurs et de graphiques simples.\n\n\n**Documentation** :\n\n- [**Enquêtes Démographiques et de Santé (DHS)**](http://dhsprogram.com/)\n\n- [**Statistique descriptive univariée et bivariée** de H.Pecout et T.Giraud ](http://huguespecout.github.io/Initiation_R_stats/)\n\n- [Les **jointures avec R** par L. Vaudor](http://perso.ens-lyon.fr/lise.vaudor/combinaisons-et-jointures-de-tables-avec-dplyr/)\n\n\n**Installation des packages** : \n\n```markdown\ninstall.packages(\"readstata13\")\ninstall.packages(\"rio\")\ninstall.packages(\"dyplyr\")\ninstall.packages(\"questionr\")\n```\n\n**Fichiers à disposition** :\n\nLes fichiers contiennent 10% des individus des tables téléchargées du site [enquêtes DHS](https://dhsprogram.com/) au *format Stata* (.dta) et rassemblent les réponses de l'enquête passée au Bénin en 2017 (vague 7).\n\nNous utilisons ici uniquement les fichiers *niveau Ménages*, *niveau Femmes*, et *niveau Enfants* de l'enquête passée au Bénin en 2017 (vague 7). Ces fichiers sont initialement au *format Stata* (.dta). \n\n| Pays  | Niveau Ménages | Niveau Femmes | Niveau Enfants |\n|-------|----------------|---------------|----------------|\n| Bénin | B1_BN          | B2_BN         | B4_BN          |\n\nOn va selectionner quelques variables à partir des fichiers initiaux.\n\n\n\n## Appel des packages\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(readstata13)\nlibrary(rio)\nlibrary(dplyr)\nlibrary(questionr)\nlibrary(tidyverse)\nlibrary(esquisse)\n```\n:::\n\n\n# Création de tables R à partir de fichiers Stata\n\n* Table *BE_Menages*\n\nOn lit le fichier contenant les caractéristiques des logements des *Ménages* et on sélectionne les variables suivantes :\n\n| Variable | Label / Intitulé                        |\n|----------|-----------------------------------------|\n| hhid     | Case Identification                     |\n| hv000    | Country code and phase                  |\n| hv001    | Cluster number                          |\n| hv002    | Household number                        |\n| hv003    | Respondent's line number                |\n| hv024    | Region                                  |\n| hv025    | Type of place of residence              |\n| hv219    | Sex of head of household                |\n| hv220    | Age of head of household                |\n| hv219    | Has telephone (land-line)               |\n| hv227    | Has mosquito bed net for sleeping       |\n| hv230b   | Presence of water at hand washing place |\n\n\n::: {.cell}\n\n```{.r .cell-code}\nBe_Menages = read.dta13(\"datas/B1_BN.dta\",generate.factors=T,fromEncoding=\"latin1\") %>%\n  factorize()  %>%\n  data.frame() %>% \n    # Selection des variables\n  select(c(hhid,hv000,hv001,hv002,hv003,hv024,hv025,hv230b,hv227,hv219,hv220,hv221)) \n```\n:::\n\n::: {.cell filename='Afficher le contenu de la table '}\n\n```{.r .cell-code}\n  str(Be_Menages)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n'data.frame':\t1416 obs. of  12 variables:\n $ hhid  : chr  \"       1  46\" \"       1 119\" \"       1 131\" \"       1 143\" ...\n $ hv000 : chr  \"BJ7\" \"BJ7\" \"BJ7\" \"BJ7\" ...\n $ hv001 : int  1 1 1 1 2 3 3 4 6 6 ...\n $ hv002 : int  46 119 131 143 25 11 47 149 37 63 ...\n $ hv003 : Factor w/ 10 levels \"incomplete household\",..: 5 2 5 2 2 2 5 5 5 2 ...\n $ hv024 : Factor w/ 12 levels \"alibori\",\"atacora\",..: 1 1 1 1 1 1 1 1 1 1 ...\n $ hv025 : Factor w/ 2 levels \"urban\",\"rural\": 2 2 2 2 2 2 2 2 2 2 ...\n $ hv230b: Factor w/ 2 levels \"water not available\",..: NA NA NA NA 1 NA NA 1 NA 1 ...\n $ hv227 : Factor w/ 2 levels \"no\",\"yes\": 2 2 1 1 2 1 2 2 2 2 ...\n $ hv219 : Factor w/ 2 levels \"male\",\"female\": 1 1 1 1 1 2 1 1 1 1 ...\n $ hv220 : Factor w/ 78 levels \"16\",\"17\",\"18\",..: 50 20 22 58 32 50 13 25 21 29 ...\n $ hv221 : Factor w/ 2 levels \"no\",\"yes\": 1 1 1 1 1 1 1 1 1 1 ...\n```\n:::\n:::\n\n\n\n* Table *BE_Femmes*\n\nOn lit le fichier contenant les caractéristiques des *Femmes* enquêtées et on sélectionne les variables :\n\n| Variable | Label / Intitulé                       |\n|----------|----------------------------------------|\n| caseid   | Case Identification                    |\n| v000     | Country code and phase                 |\n| v001     | Cluster number                         |\n| v002     | Household number                       |\n| v003     | Respondent's line number               |\n| v704     | Husband/partner's occupation           |\n| v705     | Husband/partner's occupation (grouped) |\n| v716     | Respondent's occupation                |\n| v149     | Educational attainment                 |\n\n\n::: {.cell}\n\n```{.r .cell-code}\nBe_Femmes = read.dta13(\"datas/B2_BN.dta\",generate.factors=T,fromEncoding=\"latin1\") %>%\n  factorize() %>%\n  data.frame() %>% \n    # Selection des variables \n  select(c(caseid,v000,v001,v002,v003,v704,v705,v716,v149))\n```\n:::\n\n::: {.cell filename='Afficher le contenu de la table '}\n\n```{.r .cell-code}\n  str(Be_Femmes)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n'data.frame':\t1593 obs. of  9 variables:\n $ caseid: chr  \"       1  15  4\" \"       1  46  2\" \"       1  46  5\" \"       1  52  5\" ...\n $ v000  : chr  \"BJ7\" \"BJ7\" \"BJ7\" \"BJ7\" ...\n $ v001  : int  1 1 1 1 1 1 2 2 3 3 ...\n $ v002  : int  15 46 46 52 76 119 13 76 2 13 ...\n $ v003  : int  4 2 5 5 2 3 2 9 27 2 ...\n $ v704  : Factor w/ 238 levels \"not working and didn't work in last 12 months\",..: 130 23 126 22 7 5 237 22 1 150 ...\n $ v705  : Factor w/ 12 levels \"did not work\",..: 4 6 4 6 5 5 11 6 1 4 ...\n $ v716  : Factor w/ 238 levels \"not working and didn't work in last 12 months\",..: 232 159 153 1 156 1 156 1 64 156 ...\n $ v149  : Factor w/ 6 levels \"no education\",..: 2 1 1 1 1 1 1 1 1 4 ...\n```\n:::\n:::\n\n\n*  Table *BE_Enfants*\n\nOn lit le fichier contenant les caractéristiques des *Enfants* (avec Education et santé) et on sélectionne les variables :\n\n| Variable | Label / Intitulé                          |\n|----------|-------------------------------------------|\n| caseid   | Case Identification                       |\n| v001     | Cluster number                            |\n| v002     | Household number                          |\n| v003     | Respondent's line number                  |\n| v716     | Respondent's occupation                   |\n| v717     | Respondent's occupation (grouped)         |\n| v719     | Respondent works for family, others, self |\n| v218     | Number of living children                 |\n| v130     | Religion                                  |\n| v131     | Ethnicity                                 |\n| v101     | Region                                    |\n| v102     | Type of place of residence                |\n| v106     | Highest educational level                 |\n| v107     | Highest year of education                 |\n| v113     | Source of drinking water                  |\n| v115     | Time to get to water source               |\n\n\n::: {.cell}\n\n```{.r .cell-code}\nBe_Enfants = read.dta13(\"datas/B4_BN.dta\",generate.factors=T,fromEncoding=\"latin1\") %>%\n  factorize() %>%\n  data.frame() %>% \n\n# Selection des variables \n  select(c(caseid,v000,v001,v002,v003,v716,v717,v719,v218,v130,v131,v101,v102,v106,v107,v113,v115))\n```\n:::\n\n::: {.cell filename='Afficher le contenu de la table '}\n\n```{.r .cell-code}\n  str(Be_Enfants)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n'data.frame':\t1359 obs. of  17 variables:\n $ caseid: int  225 482 532 563 642 1212 1648 2258 3135 3178 ...\n $ v000  : chr  \"BJ7\" \"BJ7\" \"BJ7\" \"BJ7\" ...\n $ v001  : int  2 4 5 5 6 1 1 2 3 3 ...\n $ v002  : int  2 8 3 6 4 21 64 25 13 17 ...\n $ v003  : int  5 2 2 3 2 2 8 8 5 8 ...\n $ v716  : Factor w/ 238 levels \"not working and didn't work in last 12 months\",..: 23 4 62 156 156 153 1 1 62 153 ...\n $ v717  : Factor w/ 12 levels \"not working\",..: 6 5 9 4 4 4 1 1 9 4 ...\n $ v719  : Factor w/ 3 levels \"for family member\",..: 1 3 3 3 3 3 NA NA 3 3 ...\n $ v218  : int  1 2 4 4 5 4 5 1 3 5 ...\n $ v130  : Factor w/ 11 levels \"vodoun\",\"other traditional\",..: 3 4 3 10 3 3 3 3 3 3 ...\n $ v131  : Factor w/ 10 levels \"adja and related\",..: 2 2 2 2 7 2 7 7 2 2 ...\n $ v101  : Factor w/ 12 levels \"alibori\",\"atacora\",..: 1 1 1 1 1 1 1 1 1 1 ...\n $ v102  : Factor w/ 2 levels \"urban\",\"rural\": 2 2 2 2 2 2 2 2 2 2 ...\n $ v106  : Factor w/ 4 levels \"no education\",..: 1 1 1 1 1 1 1 1 1 1 ...\n $ v107  : Factor w/ 8 levels \"no years completed at level v106\",..: NA NA NA NA NA NA NA NA NA NA ...\n $ v113  : Factor w/ 21 levels \"piped water\",..: 10 10 9 14 10 10 10 21 10 10 ...\n $ v115  : Factor w/ 33 levels \"0\",\"1\",\"10\",\"100\",..: 3 3 31 3 18 14 31 32 31 14 ...\n```\n:::\n:::\n\n\nLa variable *caseid* de la table *Enfants* du *Bénin* est de type *entier (int)* alors que la variable *caseid* d'autres tables *Enfants* (par exemple du *Togo* ou du *Mali*) est *chaîne de caractères (char)*. On va changer son type en chaîne de caractères avec la fonction **`mutate`** à laquelle sera associée une autre fonction: `as.character`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nBe_Enfants= Be_Enfants %>%\n   mutate(caseid=as.character(caseid)) \n```\n:::\n\n\n# Comprendre l'organisation des tables entre elles\n\nOn s'attache en particulier aux identifiants des individus de chacune des tables *Menages*, *Femmes* et *Enfants* pour en comprendre l'organisation et les liens possibles entre elles.\n\n* **Table ménage**\n\n| Variable | Label / Intitulé                                             |\n|----------|--------------------------------------------------------------|\n| hhid     | Case Identification                                          |\n| hv001    | Cluster number                                               |\n| hv002    | Household number                                             |\n| hv003    | Respondent's line number (answering Household questionnaire) |\n| ...      | ...                                                          |\n\n* **Table Femmes et table Enfants**\n\n| Variable | Label / Intitulé         |\n|----------|--------------------------|\n| caseid   | Case Identification      |\n| v001     | Cluster number           |\n| v002     | Household number         |\n| v003     | Respondent's line number |\n| ...      | ...                      |\n\nOn pourra reconstituer le numéro du ménage à laquelle appartient chaque femme de la table *Femmes* à l'aide des variables v001, v002 et v003 qui sont des chaînes de caractères (char) que l'on pourra concaténer avec la fonction **`paste`** (casesid=v001+v002+v003).\n\nPour illuster ce propos, nous pouvons regarder l'organisation de fichiers issus de 5 ménages enquêtés au Togo en 2013.\n\n![](img/img1.png){width=\"90%\"}\n\n*Caseid,* l'identifiant du premier enfant de la table *Enfants*, a pour valeur *4962*. Il appartient au 1er ménage de la table *Ménages.*\n\nLes 5e et 6e enfants de la table *Enfants* appartiennent au 5e ménage de la table *Ménages* et on retrouve la correspondance avec la table *Femmes*.\n\nOn pourra donc faire des jointures entre les tables *Ménages*, *Femmes* et *Enfants*.\n\n\n# Statistiques univariées\n\n## Afficher le contenu des tables\n\nPour rappel, la fonction `str(matable)` permet d'afficher le nombre d'observations et de variables d'une table R mais aussi son *type* qui conditionne l'utilisation de fonctions.\n\nUne variable qualitative peut être stockée en *factor* ou *character* et une variable numérique en *integer* pour des nombres entiers).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstr(Be_Menages)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n'data.frame':\t1416 obs. of  12 variables:\n $ hhid  : chr  \"       1  46\" \"       1 119\" \"       1 131\" \"       1 143\" ...\n $ hv000 : chr  \"BJ7\" \"BJ7\" \"BJ7\" \"BJ7\" ...\n $ hv001 : int  1 1 1 1 2 3 3 4 6 6 ...\n $ hv002 : int  46 119 131 143 25 11 47 149 37 63 ...\n $ hv003 : Factor w/ 10 levels \"incomplete household\",..: 5 2 5 2 2 2 5 5 5 2 ...\n $ hv024 : Factor w/ 12 levels \"alibori\",\"atacora\",..: 1 1 1 1 1 1 1 1 1 1 ...\n $ hv025 : Factor w/ 2 levels \"urban\",\"rural\": 2 2 2 2 2 2 2 2 2 2 ...\n $ hv230b: Factor w/ 2 levels \"water not available\",..: NA NA NA NA 1 NA NA 1 NA 1 ...\n $ hv227 : Factor w/ 2 levels \"no\",\"yes\": 2 2 1 1 2 1 2 2 2 2 ...\n $ hv219 : Factor w/ 2 levels \"male\",\"female\": 1 1 1 1 1 2 1 1 1 1 ...\n $ hv220 : Factor w/ 78 levels \"16\",\"17\",\"18\",..: 50 20 22 58 32 50 13 25 21 29 ...\n $ hv221 : Factor w/ 2 levels \"no\",\"yes\": 1 1 1 1 1 1 1 1 1 1 ...\n```\n:::\n:::\n\n\nLa table contient 1416 observations et 12 variables. On dénombre 1416 ménages au Bénin.\n\nLa variable *hhid* (identifiant du ménage) est de type character (char), la variable *hv001* (cluster number) est de type entier (int) et la variable *hv003* (numéro du répondant) est de type facteur (Factor).\n\n## Répartition des ménages ...\n\n*  **Selon le type de commune**\n\nLa variable *hv025* (milieu rural ou urbain) est une variable qualitative de type *facteur* (Factor) .\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Comme la variable est de type Factor on peut utiliser la fonction summary qui va afficher les effectif\nsummary(Be_Menages$hv025)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nurban rural \n  616   800 \n```\n:::\n\n```{.r .cell-code}\n# On utilise la fonction freq du package questionr pour afficher aussi les %\nfreq(Be_Menages$hv025, cum=F)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n        n    % val%\nurban 616 43.5 43.5\nrural 800 56.5 56.5\n```\n:::\n:::\n\n\nOn trouve 800 Menages habitant en milieu rural, soit près de 57% des ménages interrogés au Bénin dans notre échantillon.\n\n* **...Selon le fait de posséder une moustiquaire**\n\nOn prend la variable *hv227:Has mosquito bed net for sleeping* de la table *Ménages* pour calculer la répartition et faire le graphique associé\n\n\n::: {.cell filename='Répartition'}\n\n```{.r .cell-code}\nfreq(Be_Menages$hv227, cum=F)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n       n    % val%\nno    89  6.3  6.3\nyes 1327 93.7 93.7\n```\n:::\n:::\n\n::: {.cell filename='Graphique'}\n\n```{.r .cell-code}\nggplot(Be_Menages) +\n  aes(x = hv227) +\n  geom_bar(position = \"dodge\", fill = \"#112446\") +\n  coord_flip() +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](dhs_files/figure-html/unnamed-chunk-11-1.png){width=672}\n:::\n:::\n\n\nPrès de 94% des ménages de notre fichier possèdent une moustiquaire pour dormir.\n\n* **...Selon l'accès à l'eau pour se laver les mains**\n\nOn prend la variable *hv230b* (*Presence of water at hand washing place*) de la table *Ménages*\n\n\n::: {.cell filename='Répartition'}\n\n```{.r .cell-code}\n# Répartition\nfreq(Be_Menages$hv230b, cum=F)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n                      n    % val%\nwater not available 441 31.1   57\nwater is available  333 23.5   43\nNA                  642 45.3   NA\n```\n:::\n:::\n\n::: {.cell filename='Graphique'}\n\n```{.r .cell-code}\nggplot(Be_Menages) +\n  aes(x = hv230b) +\n  geom_bar(position = \"dodge\", fill = \"#112446\") +\n  coord_flip() +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](dhs_files/figure-html/unnamed-chunk-13-1.png){width=672}\n:::\n:::\n\n\nParmi les répondants à cette question (près de 55% des ménages), seulement près d'un tiers a accès à l'eau pour se laver les mains.\n\n* **...Selon l'âge des chefs de ménage**\n\nLa variable hv220 (age) est de type *facteur*, on peut calculer la répartition.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfreq(Be_Menages$hv220,cum=T)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n            n   % val%  %cum val%cum\n16          2 0.1  0.1   0.1     0.1\n17          1 0.1  0.1   0.2     0.2\n18          2 0.1  0.1   0.4     0.4\n19          5 0.4  0.4   0.7     0.7\n20          6 0.4  0.4   1.1     1.1\n21          9 0.6  0.6   1.8     1.8\n22         17 1.2  1.2   3.0     3.0\n23         17 1.2  1.2   4.2     4.2\n24         17 1.2  1.2   5.4     5.4\n25         41 2.9  2.9   8.3     8.3\n26         17 1.2  1.2   9.5     9.5\n27         29 2.0  2.0  11.5    11.5\n28         49 3.5  3.5  15.0    15.0\n29         30 2.1  2.1  17.1    17.1\n30         55 3.9  3.9  21.0    21.0\n31         29 2.0  2.0  23.0    23.0\n32         52 3.7  3.7  26.7    26.7\n33         31 2.2  2.2  28.9    28.9\n34         30 2.1  2.1  31.0    31.0\n35         51 3.6  3.6  34.6    34.6\n36         18 1.3  1.3  35.9    35.9\n37         43 3.0  3.0  38.9    38.9\n38         28 2.0  2.0  40.9    40.9\n39         26 1.8  1.8  42.7    42.7\n40         53 3.7  3.7  46.5    46.5\n41         35 2.5  2.5  48.9    48.9\n42         32 2.3  2.3  51.2    51.2\n43         28 2.0  2.0  53.2    53.2\n44         18 1.3  1.3  54.4    54.4\n45         61 4.3  4.3  58.8    58.8\n46         21 1.5  1.5  60.2    60.2\n47         37 2.6  2.6  62.9    62.9\n48         17 1.2  1.2  64.1    64.1\n49         24 1.7  1.7  65.7    65.7\n50         25 1.8  1.8  67.5    67.5\n51         13 0.9  0.9  68.4    68.4\n52         27 1.9  1.9  70.3    70.3\n53         16 1.1  1.1  71.5    71.5\n54         11 0.8  0.8  72.2    72.2\n55         30 2.1  2.1  74.4    74.4\n56         17 1.2  1.2  75.6    75.6\n57         33 2.3  2.3  77.9    77.9\n58         17 1.2  1.2  79.1    79.1\n59          7 0.5  0.5  79.6    79.6\n60         31 2.2  2.2  81.8    81.8\n61         17 1.2  1.2  83.0    83.0\n62         20 1.4  1.4  84.4    84.4\n63         11 0.8  0.8  85.2    85.2\n64          3 0.2  0.2  85.4    85.4\n65         26 1.8  1.8  87.2    87.2\n66         13 0.9  0.9  88.1    88.1\n67         15 1.1  1.1  89.2    89.2\n68         19 1.3  1.3  90.5    90.5\n69         11 0.8  0.8  91.3    91.3\n70         26 1.8  1.8  93.1    93.1\n71         14 1.0  1.0  94.1    94.1\n72         10 0.7  0.7  94.8    94.8\n73          7 0.5  0.5  95.3    95.3\n74          4 0.3  0.3  95.6    95.6\n75         10 0.7  0.7  96.3    96.3\n76          5 0.4  0.4  96.7    96.7\n77          7 0.5  0.5  97.2    97.2\n78          6 0.4  0.4  97.6    97.6\n79          2 0.1  0.1  97.7    97.7\n80          9 0.6  0.6  98.4    98.4\n81          3 0.2  0.2  98.6    98.6\n82          3 0.2  0.2  98.8    98.8\n83          1 0.1  0.1  98.9    98.9\n84          1 0.1  0.1  98.9    98.9\n85          6 0.4  0.4  99.4    99.4\n86          1 0.1  0.1  99.4    99.4\n87          2 0.1  0.1  99.6    99.6\n88          1 0.1  0.1  99.6    99.6\n90          2 0.1  0.1  99.8    99.8\n92          2 0.1  0.1  99.9    99.9\n95          1 0.1  0.1 100.0   100.0\n97+         0 0.0  0.0 100.0   100.0\ndon't know  0 0.0  0.0 100.0   100.0\n```\n:::\n:::\n\n\nLes modalités de la variable *h220* sont ordonnées, le calcul des fréquences cumulées a un sens et on peut dire que la moité des chefs de ménages a moins de 42 ans.\n\n\n## Composition des ménages\n\nIci on se sert des informations des tables *Femmes* et *Enfants* pour calculer leur nombre dans les ménages de notre échantillon ... On crée un *identifiant ménage (hhid)* pour chacune des tables. Et on ajoute ce nouvelle variable dans chacune des tables.\n\n* **Nombre de femmes par ménage** \n\nOn génère un compteur pour calculer le nombre de femmes par ménages (qui ont un identifiant de ménage identique): *Nbfem*. On ajoute cette nouvelle variable dans la table Femmes. Cette variable est une variable numérique de type *integer* (int) dans R. On peut alors calculer la répartition du nombre de femmes dans les menages.\n\n\n::: {.cell filename='création de la variable nombre de femmes par ménage'}\n\n```{.r .cell-code}\nBe_Femmes2<-Be_Femmes%>% \n  mutate(hhid=paste(v001,v002,sep=\" \"))\n# On générère la variable nombreb de femmes par ménage : Nbfem\nBe_Femmes3=Be_Femmes2 %>%\n  group_by(hhid) %>%\n  summarise(Nbfem = n())\n```\n:::\n\n::: {.cell filename='Récupération de la variable Nbfem dans la table'}\n\n```{.r .cell-code}\n# On ajoute les variables de la table avec le nombre de femmes dans la table femme \nBe_Femmes22<-Be_Femmes3 %>%\n  left_join(Be_Femmes2,by=\"hhid\")\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Si variable numérique\nsummary(Be_Femmes22$Nbfem)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n  1.000   1.000   1.000   1.102   1.000   4.000 \n```\n:::\n\n```{.r .cell-code}\n# Si variable discrète\ntable(Be_Femmes22$Nbfem)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n   1    2    3    4 \n1445  138    6    4 \n```\n:::\n:::\n\n\nOn dénombre 1445 ménages composés d'une femme, 138 de 2 femmes et 10 ménages de 3 ou 4 femmes dans l'echantillon extrait de l'enquête passée au Bénin.\n\n* Nombre moyen d'enfants vivants dans les ménages\n\nOn peut calculer et représenter sur un graphique le nombre d'enfants vivants (*v218:Number of living children*)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(Be_Enfants$v218)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n  0.000   2.000   3.000   3.491   5.000  10.000 \n```\n:::\n:::\n\n\nParmi les enfants vivants de la table *Enfants* on trouve au minimum 0 enfants vivants et 10 au maximum. On trouve en moyenne 3,5 enfants vivants par ménages et la moitié des ménages enquêtés ont 3 enfants.\n\nOn peut visualiser ces statistiques sur un graphique de type Box-Plot. Le code *ggplot* a été récupéré à partir d'un graphique généré avec **esquisse** [lien fiche](https://mthevenin.github.io/assistoolsms/R/assist/posts/addins/addins.html#addins-esquisse)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(Be_Enfants) +\n  aes(x = \"\", y = v218) +\n  geom_boxplot(fill = \"#526747\") +\n  theme_classic()\n```\n\n::: {.cell-output-display}\n![](dhs_files/figure-html/unnamed-chunk-19-1.png){width=672}\n:::\n:::\n",
    "supporting": [
      "dhs_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}